import type { Lang } from "./lang";

/** Copy halaman pricing. Semua angka di sini mengikuti quota.ts dan plan-limits.ts. */
export function pricingCopy(lang: Lang) {
  const en = lang === "en";
  return {
    eyebrow: en ? "Plans for every build pace" : "Paket untuk setiap ritme build",
    heroTitle: en ? "Pick the plan that fits your build." : "Pilih paket sesuai ritme build kamu.",
    heroSub: en ? "Both plans turn a brief into a structured plan, PRD, architecture, and ordered tasks. The limits and editing tools are different." : "Kedua paket mengubah brief menjadi struktur plan, PRD, arsitektur, dan task terurut. Batas penggunaan dan alat editnya yang berbeda.",
    pipeline: en ? ["Brief", "Plan structure", "PRD", "Architecture", "Ordered tasks"] : ["Brief", "Struktur plan", "PRD", "Arsitektur", "Task terurut"],
    currencyNote: en ? "Prices in IDR" : "Harga dalam Rupiah",
    plansTitle: en ? "Plans" : "Paket",
    freeDescription: en ? "For trying the full planning flow." : "Untuk mencoba seluruh alur planning.",
    proDescription: en ? "For frequent builds and deeper plans." : "Untuk build rutin dan plan yang lebih dalam.",
    chooseFree: en ? "Choose Free" : "Pilih Free",
    choosePro: en ? "Choose Pro" : "Pilih Pro",
    freeWhy: en ? "Why choose Free?" : "Kenapa pilih Free?",
    proWhy: en ? "Why choose Pro?" : "Kenapa pilih Pro?",
    included: en ? "Includes:" : "Termasuk:",
    freeReasons: en ? ["3 successful plan generations in a rolling 24-hour window", "4 to 8 phases per plan", "3 to 5 sub-features per phase", "8 to 12 tasks per phase"] : ["3 generate plan yang berhasil dalam rolling 24 jam", "4 sampai 8 fase per plan", "3 sampai 5 sub-fitur per fase", "8 sampai 12 task per fase"],
    proReasons: en ? ["Unlimited successful plan generations", "10 to 15 phases per plan", "12 to 20 sub-features per phase", "15 to 25 tasks per phase", "Add up to 2 ideas to each project", "Delete phases, sub-features, and idle tasks"] : ["Generate plan berhasil tanpa batas kuota", "10 sampai 15 fase per plan", "12 sampai 20 sub-fitur per fase", "15 sampai 25 task per fase", "Tambahkan maksimal 2 ide ke setiap project", "Hapus fase, sub-fitur, dan task yang tidak sedang berjalan"],
    monthly: en ? "Monthly" : "Bulanan",
    quarterly: en ? "3 months" : "3 bulan",
    save: en ? "Save 20%" : "Hemat 20%",
    perMonth: en ? "/month" : "/bulan",
    perQuarter: en ? "/3 months" : "/3 bulan",
    freePrice: "Rp 0",
    monthlyPrice: "Rp 39rb",
    quarterlyPrice: "Rp 93,6rb",
    quarterlyOriginal: "Rp 117rb",
    compareTitle: en ? "Compare every plan detail" : "Bandingkan detail tiap paket",
    compareSub: en ? "The limits below are enforced by ScratchAgent when it generates or edits a plan." : "Batas di bawah ini diterapkan langsung oleh ScratchAgent saat membuat atau mengedit plan.",
    featureLabel: en ? "Feature" : "Fitur",
    comparison: [
      { label: en ? "Successful generations per rolling 24 hours" : "Generate berhasil per rolling 24 jam", free: "3", pro: en ? "Unlimited" : "Tanpa batas" },
      { label: en ? "Phases per plan" : "Fase per plan", free: "4-8", pro: "10-15" },
      { label: en ? "Sub-features per phase" : "Sub-fitur per fase", free: "3-5", pro: "12-20" },
      { label: en ? "Tasks per phase" : "Task per fase", free: "8-12", pro: "15-25" },
      { label: en ? "Add ideas after generation" : "Tambah ide setelah generate", free: en ? "Not included" : "Tidak termasuk", pro: en ? "Up to 2 per project" : "Maks. 2 per project" },
      { label: en ? "Delete plan structure" : "Hapus struktur plan", free: en ? "Not included" : "Tidak termasuk", pro: en ? "Included" : "Termasuk" },
    ],
    faqTitle: en ? "Pricing FAQs" : "FAQ pricing",
    faqs: en ? [
      { q: "What counts as one generation?", a: "A generation is counted after ScratchAgent successfully saves a complete plan. If generation fails, the quota slot is returned." },
      { q: "When does the Free quota reset?", a: "Free uses a rolling 24-hour window. Each successful generation leaves the window 24 hours after it was created, which opens one slot again." },
      { q: "What changes when I choose Pro?", a: "Pro removes the generation quota, raises the enforced plan structure limits, lets you add up to two ideas per project, and lets you delete phases, sub-features, or tasks that are not running." },
      { q: "How does the 3-month price work?", a: "One month costs Rp 39,000. Three months cost Rp 93,600 instead of Rp 117,000, a 20% reduction for that billing period." },
      { q: "Can a running task be deleted?", a: "No. ScratchAgent blocks deletion while a task is in progress so the plan does not conflict with the connected coding agent." },
      { q: "Do Free and Pro use the same planning flow?", a: "Yes. Both run the same stages: plan structure, PRD, architecture, database schema, and ordered tasks. The enforced size limits and Pro editing tools differ." },
    ] : [
      { q: "Apa yang dihitung sebagai satu generate?", a: "Generate dihitung setelah ScratchAgent berhasil menyimpan plan lengkap. Kalau proses generate gagal, slot kuotanya dikembalikan." },
      { q: "Kapan kuota Free kembali tersedia?", a: "Free memakai rolling 24 jam. Setiap generate yang berhasil keluar dari jendela hitung 24 jam setelah dibuat, lalu satu slot terbuka lagi." },
      { q: "Apa yang berubah saat memilih Pro?", a: "Pro menghapus batas kuota generate, menaikkan batas struktur plan, membuka penambahan maksimal dua ide per project, serta mengizinkan penghapusan fase, sub-fitur, atau task yang tidak sedang berjalan." },
      { q: "Bagaimana hitungan harga 3 bulan?", a: "Harga satu bulan Rp 39.000. Paket tiga bulan Rp 93.600 dari harga normal Rp 117.000, jadi potongannya 20% untuk periode tersebut." },
      { q: "Apakah task yang sedang berjalan bisa dihapus?", a: "Tidak. ScratchAgent menolak penghapusan task yang sedang berjalan agar struktur plan tidak bentrok dengan coding agent yang terhubung." },
      { q: "Apakah alur planning Free dan Pro sama?", a: "Ya. Keduanya menjalankan tahap struktur plan, PRD, arsitektur, database schema, dan task terurut. Batas ukuran plan dan alat edit Pro yang berbeda." },
    ],
    footnote: en ? "Generation limits count successful plans. Failed generations return their quota slot." : "Batas generate menghitung plan yang berhasil. Generate yang gagal mengembalikan slot kuota.",
    footer: en ? "ScratchAgent turns a brief into work your coding agent can follow." : "ScratchAgent mengubah brief menjadi pekerjaan yang bisa diikuti coding agent.",
  };
}
